# Vagrantfile simple pour une VM Ubuntu 20.04

Vagrant.configure("2") do |config|
    # Utilisation de l'image Ubuntu 20.04
    config.vm.box = "generic/ubuntu1804"
  
    # Configuration du réseau (redirection de port)
    config.vm.network "forwarded_port", guest: 80, host: 8080
    config.vm.synced_folder ".", "/vagrant", type: "nfs", nfs_version: 4, nfs_udp: false

    # Configuration des ressources (mémoire et CPU)
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 2
    end
  end