Vagrant.configure("2") do |config|

    config.vm.define "mlecherbS" do |server|

        server.vm.box = "generic/ubuntu1804"

        server.vm.hostname = "mlecherbS"

        server.vm.network "private_network", ip: "192.168.56.110"

        server.vm.synced_folder ".", "/vagrant", type: "nfs", nfs_version: 4, nfs_udp: false

        server.vm.provider :libvirt do |libvirt|
          libvirt.memory = 1024
          libvirt.cpus = 1
        end

        server.vm.provision "shell", path: "./scripts/init_server_k3s.sh"

      end

      config.vm.define "mlecherbSW" do |serverworker|

        serverworker.vm.box = "generic/ubuntu1804"

        serverworker.vm.hostname = "mlecherbSW"

        serverworker.vm.network "private_network", ip: "192.168.56.111"

        serverworker.vm.synced_folder ".", "/vagrant", type: "nfs", nfs_version: 4, nfs_udp: false

        serverworker.vm.provider :libvirt do |libvirt|
          libvirt.memory = 1024
          libvirt.cpus = 1
        end
        serverworker.vm.provision "shell", path: "./scripts/init_agent_k3s.sh"

      end


end